### ISSUE TITLE
Error: ENOENT: no such file or directory, open '../../contact.json'

### ISSUE THREAD

**Issue by ariebrainware** [Stackfinite/connecc#9]
https://github.com/Stackfinite/connecc/blob/31f8bba101a1a12f545204861e4ae220e74d730b/lib/api/index.js#L3-L4

![image](https://user-images.githubusercontent.com/26453961/43682205-9a1be766-9897-11e8-91a8-25faa06d86a1.png)
![image](https://user-images.githubusercontent.com/26453961/43682196-087df89e-9897-11e8-9f34-7d380f2a80c0.png)

@mhaidarh @michaeltamsil @indrolie

**Comment by indrolie** [comment]
the directory should be './data/contact.json'

we should use: const JSONpath = './data/contact.json'
